### ISSUE TITLE
can't even start playing!

### ISSUE THREAD

**Issue by itslemcy** [wassgha/FaceRecognitionAPI#2]
this is what i get when i launch the py:
could help out?
```
mbpxp001:FaceRecognitionAPI-master lcordioli$ python3 /Users/lcordioli/Downloads/FaceRecognitionAPI-master/manage.py migrate
Traceback (most recent call last):
  File "/Users/lcordioli/Downloads/FaceRecognitionAPI-master/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lcordioli/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/lcordioli/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lcordioli/Downloads/FaceRecognitionAPI-master/facerec/urls.py", line 6, in <module>
    from api import views
  File "/Users/lcordioli/Downloads/FaceRecognitionAPI-master/api/views.py", line 60, in <module>
    recognizer = cv2.face.createLBPHFaceRecognizer()
AttributeError: module 'cv2.face' has no attribute 'createLBPHFaceRecognizer'
```

**Comment by wassgha** [comment]
This is caused by an opencv version mismatch, try this https://stackoverflow.com/questions/45655699/attributeerror-module-cv2-face-has-no-attribute-createlbphfacerecognizer

**Comment by itslemcy** [comment]
thanks a lot!

**Comment by itslemcy** [comment]
another question, how does the training part work?
can you show me an example of training request?
thanks a lot for your help.

**Comment by wassgha** [comment]
You train by making a get request to `/train/` as follows:
```js
{
    imageBase64: `data:image/png;base64,iVBO...`,
    user: `exampleUsername` /* also name of the folder that will be created */
}
```

Right now it is very primitive, I will need to turn this into a post request to make sure we don't exceed the maximum GET request length and I need to add some form of user management
